### ISSUE TITLE
drac_setting providers are broken.

### ISSUE THREAD

**Issue by malreynolds** [newrelic/puppet-dell#1]
Hi, I tried using your module as described in the documentation, but it looks like the providers for drac_setting don't work.

For example, I have this very simple piece of code to update the hostname:

``` ruby
... 
  # set the hostname
  drac_setting { 'cfgLanNetworking/cfgDNSRacName':
    object_value => "${::hostname}-drac",
    require => File['/usr/bin/racadm'],
  }
...
```

but it fails with 'undefined local variable or method result'. I had a look in the provider code and it looks like all the racadm instances have been commented out about a year ago, resulting in incorrect syntax at places (i.e in this case checking the value of 'result' before it's defined in the idrac7 provider) and obviously nothing would actually update the configuration.

My question is, am I misunderstanding something, or is this module no longer supposed to support drac_setting configuration?

Thanks!

**Comment by aughr** [comment]
Sorry for the silence over here. I'm closing this issue because we're no longer maintaining this repo (as you might have been able to tell).
